baseURL = "https://cablelabs.github.io/micronets"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "CableLabs Micronets"
publishDir =  "../docs"
theme = "techdoc"

## -- Config parameters for techdoc theme
hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

#ignoreFiles = ["externalContent"]

[Params]
    # Souce Code repository section
    description = "Developer documentation for CableLabs Micronets"
    github_repository = "https://github.com/cablelabs/micronets"
    #version = "0.2.1"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/cablelabs/micronets.wiki"

    # Analytic section
    #google_analytics_id = "" # Your Google Analytics tracking id
    #tag_manager_container_id = "" # Your Google Tag Manager container id
    #google_site_verification = "" # Your Google Site Verification

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = ["archives", "externalContent"]

    # Added as part of the includeFile shortcode. See the documentation in the includeFile.html
    includes_dir = "externalContent"


# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About Micronets"
    url = "https://www.cablelabs.com/micronets"
    weight = 8
## --  End config of techdoc
